version: '3'
services:
  splunk:
    image: splunk/splunk:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=password
